/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bernie' at '2016/6/8 下午 1:11' with Gradle 2.13
 *
 * @author bernie, @date 2016/6/8 下午 1:11
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
